name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    name: Build and publish Python distro to PyPI
    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: pip install build

      - name: Build binary wheel and source tarball
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # By default, this action publishes to PyPI.
        # To configure Trusted Publishing, the user needs to set up the publisher on PyPI
        # matching this repository and workflow.
