name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          post-cleanup: 'all'

      - name: Install package
        shell: micromamba-shell {0}
        run: pip install -e .

      - name: Run unit tests
        shell: micromamba-shell {0}
        run: |
          pytest --cov=./ --cov-report=xml -n auto -v gradabeam/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
